# Generated by Django 5.1.7 on 2025-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LupusData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fever', models.BooleanField(default=False)),
                ('alopecia', models.BooleanField(default=False)),
                ('oral_ulcers', models.BooleanField(default=False)),
                ('discoidRash', models.BooleanField(default=False)),
                ('photosensitivity', models.BooleanField(default=False)),
                ('jointPain', models.BooleanField(default=False)),
                ('pleuralEffusion', models.BooleanField(default=False)),
                ('pericarditis', models.BooleanField(default=False)),
                ('delirium', models.BooleanField(default=False)),
                ('psychosis', models.BooleanField(default=False)),
                ('seizure', models.BooleanField(default=False)),
                ('renalClass2', models.BooleanField(default=False)),
                ('renalClass3', models.BooleanField(default=False)),
                ('anticardiolipin', models.BooleanField(default=False)),
                ('antiB2GPI', models.BooleanField(default=False)),
                ('lupusAnticoagulant', models.BooleanField(default=False)),
                ('urine_routine', models.FloatField()),
                ('haemoglobin', models.FloatField()),
                ('tlc', models.FloatField()),
                ('platelet_count', models.FloatField()),
                ('c3', models.FloatField()),
                ('c4', models.FloatField()),
                ('antiDsDNA', models.FloatField()),
                ('antiSmith', models.FloatField()),
            ],
        ),
    ]
