# Generated by Django 5.1.7 on 2025-03-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lupusdata',
            name='alopecia',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='antiB2GPI',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='antiDsDNA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='antiSmith',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='anticardiolipin',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='c3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='c4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='delirium',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='discoidRash',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='fever',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='haemoglobin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='jointPain',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='lupusAnticoagulant',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='oral_ulcers',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='pericarditis',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='photosensitivity',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='platelet_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='pleuralEffusion',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='psychosis',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='renalClass2',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='renalClass3',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='seizure',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='tlc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='urine_routine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
