# Generated by Django 5.1.7 on 2026-02-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_lupusdata_alopecia_alter_lupusdata_antib2gpi_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lupusdata',
            name='haemoglobin',
        ),
        migrations.AddField(
            model_name='lupusdata',
            name='hemolysis',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='antiDsDNA',
            field=models.CharField(default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='lupusdata',
            name='antiSmith',
            field=models.CharField(default='No', max_length=10),
        ),
    ]
